<?php

namespace Database\Seeders;

use App\Models\ServiceJob;
use App\Models\User;
use Illuminate\Database\Seeder;

class DemoServiceJobsSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::query()->where('email', 'hamid.hartaly@gmail.com')->firstOrFail();
        $accountant = User::query()->where('email', 'accounts@nozan-service.local')->firstOrFail();
        $technician = User::query()->where('email', 'workshop@nozan-service.local')->firstOrFail();
        $technicianTwo = User::query()->where('email', 'workshop-two@nozan-service.local')->firstOrFail();
        $cashier = User::query()->where('email', 'cashier@nozan-service.local')->firstOrFail();

        $jobs = [
            [
                'job_code' => 'NGS-260330-1001',
                'customer_id' => 'customer-260330-1001',
                'customer_name' => 'Baran Karim',
                'customer_phone' => '+964 750 222 4567',
                'tv_model' => 'LG 65" OLED',
                'category' => 'OLED',
                'issue' => 'Vertical line appeared after transport damage.',
                'technician_notes' => null,
                'priority' => 'high',
                'status' => 'PENDING',
                'estimated_price_iqd' => 120000,
                'final_price_iqd' => null,
                'repair_cost_iqd' => null,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 0,
                'assigned_staff_uid' => null,
                'repair_started_at' => null,
                'created_by_user_id' => $admin->id,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
                'finished_at' => null,
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260330-1002',
                'customer_id' => 'customer-260330-1002',
                'customer_name' => 'Soran Ahmed',
                'customer_phone' => '+964 771 333 8888',
                'tv_model' => 'Samsung 55" QLED',
                'category' => 'QLED',
                'issue' => 'Backlight fails after 15 minutes of use.',
                'technician_notes' => 'Backlight strip pack tested weak. Driver board output unstable.',
                'priority' => 'normal',
                'status' => 'REPAIR',
                'estimated_price_iqd' => 90000,
                'final_price_iqd' => null,
                'repair_cost_iqd' => 38000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 0,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subHours(4),
                'created_by_user_id' => $technician->id,
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(2),
                'finished_at' => null,
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260330-1003',
                'customer_id' => 'customer-260330-1003',
                'customer_name' => 'Dara Hassan',
                'customer_phone' => '+964 771 101 2020',
                'tv_model' => 'TCL 50" LED',
                'category' => 'LED',
                'issue' => 'Power cycling and no picture.',
                'technician_notes' => 'Power board capacitors replaced and HDMI port cleaned.',
                'priority' => 'normal',
                'status' => 'FINISHED',
                'estimated_price_iqd' => 70000,
                'final_price_iqd' => 75000,
                'repair_cost_iqd' => 25000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 30000,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subDay()->addHours(10),
                'created_by_user_id' => $admin->id,
                'created_at' => now()->subDay()->addHours(8),
                'updated_at' => now()->subHours(1),
                'finished_at' => now()->subHours(1),
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260330-1004',
                'customer_id' => 'customer-260330-1004',
                'customer_name' => 'Karzan Ali',
                'customer_phone' => '+964 750 999 9999',
                'tv_model' => 'Sony 49" LED',
                'category' => 'LED',
                'issue' => 'No sound and intermittent HDMI signal.',
                'technician_notes' => 'Audio amp module reseated and main board firmware refreshed.',
                'priority' => 'low',
                'status' => 'OUT',
                'estimated_price_iqd' => 60000,
                'final_price_iqd' => 65000,
                'repair_cost_iqd' => 18000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 65000,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subDays(2)->addHours(11),
                'created_by_user_id' => $cashier->id,
                'created_at' => now()->subDays(2)->addHours(9),
                'updated_at' => now()->subHours(3),
                'finished_at' => now()->subDay(),
                'out_at' => now()->subHours(3),
            ],
            [
                'job_code' => 'NGS-260330-1005',
                'customer_id' => 'customer-260330-1005',
                'customer_name' => 'Shler Omer',
                'customer_phone' => '+964 770 454 1234',
                'tv_model' => 'Hisense 58" Smart TV',
                'category' => 'OTHER',
                'issue' => 'System boots slowly and freezes on Wi-Fi setup.',
                'technician_notes' => 'Storage health degraded. Software reset attempted before board swap decision.',
                'priority' => 'normal',
                'status' => 'REPAIR',
                'estimated_price_iqd' => 85000,
                'final_price_iqd' => null,
                'repair_cost_iqd' => 12000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 15000,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subHours(5),
                'created_by_user_id' => $accountant->id,
                'created_at' => now()->subHours(7),
                'updated_at' => now()->subMinutes(45),
                'finished_at' => null,
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260329-1006',
                'customer_id' => 'customer-260329-1006',
                'customer_name' => 'Azad Mahmood',
                'customer_phone' => '+964 770 601 9911',
                'tv_model' => 'Toshiba 43" LED',
                'category' => 'LED',
                'issue' => 'Remote works but panel stays black after startup.',
                'technician_notes' => 'Backlight connector carbonized. Strip and connector replaced.',
                'priority' => 'high',
                'status' => 'OUT',
                'estimated_price_iqd' => 80000,
                'final_price_iqd' => 85000,
                'repair_cost_iqd' => 32000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 85000,
                'assigned_staff_uid' => (string) $technicianTwo->id,
                'repair_started_at' => now()->subDay()->subHours(11),
                'created_by_user_id' => $cashier->id,
                'created_at' => now()->subDay()->subHours(13),
                'updated_at' => now()->subDay()->subHours(2),
                'finished_at' => now()->subDay()->subHours(4),
                'out_at' => now()->subDay()->subHours(2),
            ],
            [
                'job_code' => 'NGS-260328-1007',
                'customer_id' => 'customer-260328-1007',
                'customer_name' => 'Helan Saeed',
                'customer_phone' => '+964 751 224 7788',
                'tv_model' => 'Samsung 65" QLED',
                'category' => 'QLED',
                'issue' => 'Wi-Fi disconnects and apps crash after update.',
                'technician_notes' => 'Main board storage near limit. Firmware reflash completed, monitor for board replacement.',
                'priority' => 'normal',
                'status' => 'FINISHED',
                'estimated_price_iqd' => 95000,
                'final_price_iqd' => 110000,
                'repair_cost_iqd' => 27000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 50000,
                'assigned_staff_uid' => (string) $technicianTwo->id,
                'repair_started_at' => now()->subDays(2)->addHours(9),
                'created_by_user_id' => $admin->id,
                'created_at' => now()->subDays(2)->addHours(7),
                'updated_at' => now()->subHours(10),
                'finished_at' => now()->subHours(10),
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260325-1008',
                'customer_id' => 'customer-260325-1008',
                'customer_name' => 'Rebaz Jalal',
                'customer_phone' => '+964 750 883 5588',
                'tv_model' => 'LG 32" Monitor',
                'category' => 'MONITOR',
                'issue' => 'No power light and adapter smells burnt.',
                'technician_notes' => 'Adapter and DC input stage replaced. Burn-in test passed.',
                'priority' => 'normal',
                'status' => 'OUT',
                'estimated_price_iqd' => 35000,
                'final_price_iqd' => 42000,
                'repair_cost_iqd' => 11000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 42000,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subDays(5)->addHours(10),
                'created_by_user_id' => $technician->id,
                'created_at' => now()->subDays(5)->addHours(8),
                'updated_at' => now()->subDays(4)->addHours(16),
                'finished_at' => now()->subDays(4)->addHours(14),
                'out_at' => now()->subDays(4)->addHours(16),
            ],
            [
                'job_code' => 'NGS-260322-1009',
                'customer_id' => 'customer-260322-1009',
                'customer_name' => 'Dlovan Amin',
                'customer_phone' => '+964 770 540 2200',
                'tv_model' => 'Skyworth 55" Smart TV',
                'category' => 'OTHER',
                'issue' => 'Boot loop after power outage.',
                'technician_notes' => 'Flash memory corruption confirmed. Replacement chip ordered.',
                'priority' => 'high',
                'status' => 'REPAIR',
                'estimated_price_iqd' => 130000,
                'final_price_iqd' => null,
                'repair_cost_iqd' => 22000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 40000,
                'assigned_staff_uid' => (string) $technicianTwo->id,
                'repair_started_at' => now()->subDays(8)->addHours(12),
                'created_by_user_id' => $admin->id,
                'created_at' => now()->subDays(8)->addHours(9),
                'updated_at' => now()->subDays(1),
                'finished_at' => null,
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260318-1010',
                'customer_id' => 'customer-260318-1010',
                'customer_name' => 'Lana Ibrahim',
                'customer_phone' => '+964 751 332 1144',
                'tv_model' => 'Sony 65" OLED',
                'category' => 'OLED',
                'issue' => 'Half-screen dimming on the right side.',
                'technician_notes' => 'Panel driver ribbon cleaned. Stable after extended test, customer collected.',
                'priority' => 'high',
                'status' => 'OUT',
                'estimated_price_iqd' => 140000,
                'final_price_iqd' => 150000,
                'repair_cost_iqd' => 48000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 150000,
                'assigned_staff_uid' => (string) $technicianTwo->id,
                'repair_started_at' => now()->subDays(12)->addHours(11),
                'created_by_user_id' => $cashier->id,
                'created_at' => now()->subDays(12)->addHours(8),
                'updated_at' => now()->subDays(10),
                'finished_at' => now()->subDays(10)->addHours(13),
                'out_at' => now()->subDays(10)->addHours(16),
            ],
            [
                'job_code' => 'NGS-260315-1011',
                'customer_id' => 'customer-260315-1011',
                'customer_name' => 'Zhala Rashid',
                'customer_phone' => '+964 770 415 8811',
                'tv_model' => 'Philips 50" LED',
                'category' => 'LED',
                'issue' => 'Lines on screen only when the TV warms up.',
                'technician_notes' => 'Panel ribbon pressure issue reproduced. Awaiting customer approval for partial panel repair.',
                'priority' => 'normal',
                'status' => 'PENDING',
                'estimated_price_iqd' => 78000,
                'final_price_iqd' => null,
                'repair_cost_iqd' => null,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 0,
                'assigned_staff_uid' => null,
                'repair_started_at' => null,
                'created_by_user_id' => $accountant->id,
                'created_at' => now()->subDays(15)->addHours(10),
                'updated_at' => now()->subDays(15)->addHours(10),
                'finished_at' => null,
                'out_at' => null,
            ],
            [
                'job_code' => 'NGS-260311-1012',
                'customer_id' => 'customer-260311-1012',
                'customer_name' => 'Bahar Nouri',
                'customer_phone' => '+964 750 773 9112',
                'tv_model' => 'Xiaomi 43" Smart TV',
                'category' => 'OTHER',
                'issue' => 'No sound from internal speakers, headphone output works.',
                'technician_notes' => 'Audio amplifier IC replaced and sound restored.',
                'priority' => 'low',
                'status' => 'OUT',
                'estimated_price_iqd' => 55000,
                'final_price_iqd' => 58000,
                'repair_cost_iqd' => 14000,
                'whatsapp_sent' => true,
                'payment_received_iqd' => 58000,
                'assigned_staff_uid' => (string) $technician->id,
                'repair_started_at' => now()->subDays(19)->addHours(11),
                'created_by_user_id' => $admin->id,
                'created_at' => now()->subDays(19)->addHours(9),
                'updated_at' => now()->subDays(17),
                'finished_at' => now()->subDays(17)->addHours(14),
                'out_at' => now()->subDays(17)->addHours(17),
            ],
        ];

        foreach ($jobs as $job) {
            ServiceJob::query()->updateOrCreate(
                ['job_code' => $job['job_code']],
                $job,
            );
        }
    }
}

